import { IServerPopulated } from "@/src/lib/module/common/types";
import { ITableViewField } from "@/src/Components/TableView";

export const filters = {
    serverName: 'براساس نام سرور',
}

export const serverSchemaFields: ITableViewField<IServerPopulated>[] = [
    {
        key: 'serverName',
        type: 'text',
        title: 'نام سرور',
        alt: 'نام شبکه‌ای یا نام داخلی سرور',
        viewCol: true,
    },
    {
        key: 'serverType',
        type: 'select',
        title: 'نوع سرور',
        alt: 'مشخص می‌کند سرور فیزیکی است یا مجازی',
        viewCol: true,
        options: [
            { label: 'فیزیکی', value: 'Physical' },
            { label: 'مجازی', value: 'Virtual' },
            { label: 'ابری', value: 'Cloud' },
            { label: 'کانتینر', value: 'Container' },
        ],
    },
    {
        key: 'brand',
        type: 'text',
        title: 'برند',
        alt: 'برند سرور (HP, Dell, Lenovo, …)',
        viewCol: false,
    },
    {
        key: 'model',
        type: 'text',
        title: 'مدل',
        alt: 'مدل دقیق سرور',
        viewCol: false,
    },
    {
        key: 'serialNumber',
        type: 'text',
        title: 'سریال نامبر',
        alt: 'برای موجودی، گارانتی یا پشتیبانی',
        viewCol: false,
    },
    {
        key: 'internalIP',
        type: 'text',
        title: 'IP داخلی',
        alt: 'آدرس IP داخلی شبکه',
        viewCol: true,
    },
    {
        key: 'externalIP',
        type: 'text',
        title: 'IP خارجی',
        alt: 'آدرس IP برای دسترسی از بیرون یا WAN',
        viewCol: false,
    },
    {
        key: 'os',
        type: 'text',
        title: 'سیستم‌عامل',
        alt: 'مثل Windows Server, Ubuntu, Red Hat',
        viewCol: true,
    },
    {
        key: 'osVersion',
        type: 'text',
        title: 'نسخه سیستم‌عامل',
        alt: 'شماره نسخه دقیق یا Build',
        viewCol: false,
    },
    {
        key: 'role',
        type: 'text',
        title: 'نقش سرور',
        alt: 'AD, File, Web, Database و …',
        viewCol: false,
    },
    {
        key: 'activeServices',
        type: 'tags',
        title: 'سرویس‌های فعال',
        alt: 'سرویس‌های مهم نصب‌شده روی سرور (SQL, IIS, DHCP…)',
        viewCol: false,
    },
    {
        key: 'cpuCores',
        type: 'number',
        title: 'هسته CPU',
        alt: 'تعداد و مدل هسته‌ها',
        viewCol: true,
    },
    {
        key: 'ramGB',
        type: 'number',
        title: 'RAM (GB)',
        alt: 'حجم حافظه و نوع آن',
        viewCol: true,
    },
    {
        key: 'hddCapacityGB',
        type: 'number',
        title: 'ظرفیت دیسک (GB)',
        alt: 'ظرفیت کل دیسک‌ها',
        viewCol: true,
    },
    {
        key: 'raid',
        type: 'text',
        title: 'RAID',
        alt: 'نوع آرایه RAID (0,1,5,10 و…)',
        viewCol: false,
    },
    {
        key: 'gpu',
        type: 'text',
        title: 'GPU',
        alt: 'اگر کارت گرافیک دارد',
        viewCol: false,
    },
    {
        key: 'networkInterfaces',
        type: 'text',
        title: 'کارت شبکه',
        alt: 'تعداد و سرعت کارت شبکه‌ها',
        viewCol: false,
    },
    {
        key: 'location',
        type: 'none',
        title: 'نام مرکز',
        alt: 'محل فیزیکی سرور (اتاق سرور، دیتاسنتر و…)',
        viewCol: true,
    },
    {
        key: 'perciseLocation',
        type: 'text',
        title: 'محل استقرار',
        alt: 'محل فیزیکی سرور (اتاق سرور، دیتاسنتر و…)',
        viewCol: false,
    },
    {
        key: 'rackName',
        type: 'text',
        title: 'نام رک',
        alt: 'نام رک یا کمد سرور',
        viewCol: false,
    },
    {
        key: 'hostname',
        type: 'text',
        title: 'Hostname',
        alt: 'نام شبکه‌ای یا DNS سرور',
        viewCol: true,
    },
    {
        key: 'domainOrWorkgroup',
        type: 'text',
        title: 'دامین / Workgroup',
        alt: 'عضویت در دامنه یا گروه کاری',
        viewCol: false,
    },
    {
        key: 'backupStatus',
        type: 'select',
        title: 'وضعیت بکاپ',
        alt: 'آیا پشتیبان‌گیری فعال است یا خیر',
        viewCol: true,
        options: [
            { label: 'فعال', value: 'Active' },
            { label: 'غیرفعال', value: 'Inactive' },
        ],
    },
    {
        key: 'importantSoftware',
        type: 'tags',
        title: 'نرم‌افزارهای مهم',
        alt: 'نرم‌افزارهای حیاتی یا لایسنس‌دار',
        viewCol: false,
    },
    {
        key: 'currentStatus',
        type: 'select',
        title: 'وضعیت فعلی',
        alt: 'Active / Down / Reserve',
        viewCol: true,
        options: [
            { label: 'آنلاین', value: 'Active' },
            { label: 'آفلاین', value: 'Down' },
            { label: 'رزرو', value: 'Reserved' },
        ],
    },
    {
        key: 'supportResponsible',
        type: 'text',
        title: 'مسئول پشتیبانی',
        alt: 'نام تیم یا فرد مسئول',
        viewCol: true,
    },
    {
        key: 'remoteAccess',
        type: 'text',
        title: 'دسترسی ریموت',
        alt: 'RDP / SSH / VNC یا سایر روش‌ها',
        viewCol: false,
    },
    {
        key: 'openPorts',
        type: 'tags',
        title: 'پورت‌های باز',
        alt: 'TCP/UDP باز برای مانیتورینگ یا امنیت',
        viewCol: false,
    },
    {
        key: 'notes',
        type: 'text',
        title: 'توضیحات',
        alt: 'یادداشت‌ها یا هشدارها و نکات مهم',
        viewCol: false,
    },
];
