import { IRouterPopulated } from "@/src/lib/module/common/types";
import { ITableViewField } from "../TableView";

export const filters = {
    routerName: 'براساس نام روتر',
}

export const routerSchemaFields: ITableViewField<IRouterPopulated>[]  = [
    {
        key: 'routerName',
        type: 'text',
        title: 'نام روتر',
        alt: 'نام تعریف‌شده برای روتر در شبکه',
        viewCol: true,
    },
    {
        key: 'model',
        type: 'text',
        title: 'مدل / سری ساخت',
        alt: 'مدل دقیق دستگاه (مثل CCR1009 یا Cisco 2911)',
        viewCol: true,
    },
    {
        key: 'deviceType',
        type: 'select',
        title: 'نوع دستگاه',
        alt: 'مشخص کن فیزیکی است یا مجازی',
        viewCol: true,
        options: [
            { label: 'فیزیکی', value: 'Physical' },
            { label: 'مجازی', value: 'Virtual' },
        ],
    },
    {
        key: 'brand',
        type: 'text',
        title: 'برند',
        alt: 'برند روتر (MikroTik, Cisco, Huawei, ...)',
        viewCol: true,
    },
    {
        key: 'os',
        type: 'text',
        title: 'سیستم‌عامل (OS)',
        alt: 'نام سیستم‌عامل (RouterOS، IOS، VRP و غیره)',
        viewCol: true,
    },
    {
        key: 'osVersion',
        type: 'text',
        title: 'نسخه OS',
        alt: 'نسخه فعلی سیستم‌عامل نصب‌شده',
        viewCol: false,
    },
    {
        key: 'managementIP',
        type: 'text',
        title: 'آدرس IP مدیریت',
        alt: 'IP مدیریتی برای دسترسی از راه دور یا لوکال',
        viewCol: true,
    },
    {
        key: 'lanWanIP',
        type: 'text',
        title: 'IP LAN / WAN',
        alt: 'IP شبکه داخلی و خارجی برای ارتباطات',
        viewCol: true,
    },
    {
        key: 'subnetGateway',
        type: 'text',
        title: 'Subnet Mask / Gateway',
        alt: 'جزئیات مربوط به Subnet و Gateway پیش‌فرض',
        viewCol: false,
    },
    {
        key: 'location',
        type: 'text',
        title: 'مکان فیزیکی',
        alt: 'محل نصب دستگاه (اتاق سرور، شعبه، رک ۲ و...)',
        viewCol: true,
    },
    {
        key: 'role',
        type: 'text',
        title: 'نقش / عملکرد',
        alt: 'عملکرد اصلی روتر (Core Router، Edge، Branch، VPN Gateway و...)',
        viewCol: true,
    },
    {
        key: 'vlans',
        type: 'select',
        title: 'VLANها',
        alt: 'VLANهای پیکربندی‌شده روی روتر',
        viewCol: false,
        options: [], // می‌تونی بعداً داینامیک پر کنی یا چندتایی انتخاب کنی
    },
    {
        key: 'routingProtocols',
        type: 'text',
        title: 'پروتکل‌های فعال',
        alt: 'پروتکل‌های Routing فعال (مانند OSPF، BGP، RIP و...)',
        viewCol: true,
    },
    {
        key: 'natPat',
        type: 'select',
        title: 'NAT / PAT',
        alt: 'وضعیت NAT یا PAT در شبکه',
        viewCol: true,
        options: [
            { label: 'فعال (NAT)', value: 'Enabled' },
            { label: 'PAT Only', value: 'PAT Only' },
            { label: 'غیرفعال', value: 'Disabled' },
        ],
    },
    {
        key: 'vpnTypes',
        type: 'select',
        title: 'نوع VPN',
        alt: 'نوع VPNها (IPSec، L2TP، PPTP، OpenVPN و...)',
        viewCol: false,
        options: [
            { label: 'IPSec', value: 'IPSec' },
            { label: 'L2TP/IPSec', value: 'L2TP/IPSec' },
            { label: 'PPTP', value: 'PPTP' },
            { label: 'OpenVPN', value: 'OpenVPN' },
            { label: 'WireGuard', value: 'WireGuard' },
            { label: 'SSL VPN', value: 'SSL VPN' },
        ],
    },
    {
        key: 'installationDate',
        type: 'text',
        title: 'تاریخ نصب',
        alt: 'تاریخ نصب یا راه‌اندازی اولیه روتر',
        viewCol: false,
    },
    {
        key: 'lastConfigUpdate',
        type: 'text',
        title: 'آخرین بروزرسانی پیکربندی',
        alt: 'زمان آخرین تغییر در تنظیمات',
        viewCol: false,
    },
    {
        key: 'supportResponsible',
        type: 'text',
        title: 'مسئول پشتیبانی',
        alt: 'نام شخص یا تیم مسئول پشتیبانی',
        viewCol: true,
    },
    {
        key: 'notes',
        type: 'text',
        title: 'توضیحات',
        alt: 'توضیحات اضافه مانند پورت‌های خاص، دسترسی ریموت یا هشدارها',
        viewCol: false,
    },
    {
        key: 'dhcpEnabled',
        type: 'check',
        title: 'DHCP فعال',
        alt: 'آیا DHCP Server یا Relay فعال است؟',
        viewCol: true,
    },
    {
        key: 'vpnEnabled',
        type: 'check',
        title: 'VPN فعال',
        alt: 'آیا سرویس VPN فعال است؟',
        viewCol: true,
    },
];
